// This is auto-generated by Datastar. DO NOT EDIT.

namespace StarFederation.Datastar

open System

type FragmentMergeMode =
    /// Morphs the fragment into the existing element using idiomorph.
    | Morph
    /// Replaces the inner HTML of the existing element.
    | Inner
    /// Replaces the outer HTML of the existing element.
    | Outer
    /// Prepends the fragment to the existing element.
    | Prepend
    /// Appends the fragment to the existing element.
    | Append
    /// Inserts the fragment before the existing element.
    | Before
    /// Inserts the fragment after the existing element.
    | After
    /// Upserts the attributes of the existing element.
    | UpsertAttributes

type EventType =
    /// An event for merging HTML fragments into the DOM.
    | MergeFragments
    /// An event for merging signals.
    | MergeSignals
    /// An event for removing HTML fragments from the DOM.
    | RemoveFragments
    /// An event for removing signals.
    | RemoveSignals
    /// An event for executing &lt;script/&gt; elements in the browser.
    | ExecuteScript


module Consts =
    [<Literal>]
    let DatastarKey = "datastar"

    [<Literal>]
    let Version = "1.0.0-beta.11"

    /// Default: TimeSpan.FromMilliseconds 1000
    let DefaultSseRetryDuration = TimeSpan.FromMilliseconds 1000


    /// Default: morph - Morphs the fragment into the existing element using idiomorph.
    let DefaultFragmentMergeMode = Morph

    [<Literal>]
    let DefaultFragmentsUseViewTransitions = false

    [<Literal>]
    let DefaultMergeSignalsOnlyIfMissing = false

    [<Literal>]
    let DefaultExecuteScriptAutoRemove = true

    [<Literal>]
    let DefaultExecuteScriptAttributes = "type module"

    [<Literal>]
    let DatastarDatalineSelector = "selector"

    [<Literal>]
    let DatastarDatalineMergeMode = "mergeMode"

    [<Literal>]
    let DatastarDatalineFragments = "fragments"

    [<Literal>]
    let DatastarDatalineUseViewTransition = "useViewTransition"

    [<Literal>]
    let DatastarDatalineSignals = "signals"

    [<Literal>]
    let DatastarDatalineOnlyIfMissing = "onlyIfMissing"

    [<Literal>]
    let DatastarDatalinePaths = "paths"

    [<Literal>]
    let DatastarDatalineScript = "script"

    [<Literal>]
    let DatastarDatalineAttributes = "attributes"

    [<Literal>]
    let DatastarDatalineAutoRemove = "autoRemove"

    // Cache common prefixes
    [<Literal>]
    let EventPrefix = "event: "

    [<Literal>]
    let IdPrefix = "id: "

    [<Literal>]
    let RetryPrefix = "retry: "

    [<Literal>]
    let DataPrefix = "data: "

    // Use string constants for newlines to avoid allocations
    [<Literal>]
    let NewLine = "\n"

    module FragmentMergeMode =
        let toString this =
            match this with
            | FragmentMergeMode.Morph -> "morph"
            | FragmentMergeMode.Inner -> "inner"
            | FragmentMergeMode.Outer -> "outer"
            | FragmentMergeMode.Prepend -> "prepend"
            | FragmentMergeMode.Append -> "append"
            | FragmentMergeMode.Before -> "before"
            | FragmentMergeMode.After -> "after"
            | FragmentMergeMode.UpsertAttributes -> "upsertAttributes"

    module EventType =
        let toString this =
            match this with
            | EventType.MergeFragments -> "datastar-merge-fragments"
            | EventType.MergeSignals -> "datastar-merge-signals"
            | EventType.RemoveFragments -> "datastar-remove-fragments"
            | EventType.RemoveSignals -> "datastar-remove-signals"
            | EventType.ExecuteScript -> "datastar-execute-script"
